[project]
name = "fastapi_p1"
version = "0.1.0"
description = "FastAPI Adventure"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.30.0",
    "fastapi[standard]>=0.115.6",
    "pydantic-settings>=2.7.1",
    "sqlmodel>=0.0.22",
]

[tool.ruff]
[tool.ruff.format]
quote-style = "single"
